project/users/views.py
# /project/users/views.py

#################
#### imports ####
#################

from flask import flash, redirect, render_template, request, \
    session, url_for, Blueprint
from forms import RegisterForm, LoginForm
from sqlalchemy.exc import IntegrityError
from project import db, bcrypt
from project.views import login_required
from project.models import User


################
#### config ####
################

users_blueprint = Blueprint(
    'users', __name__,
    url_prefix='/users',
    template_folder='templates',
    static_folder='static')

################
#### routes ####
################

@users_blueprint.route('/logout/')
@login_required
def logout():
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('role', None)
    session.pop('name', None)
    flash('You are logged out.')
    return redirect(url_for('users.login'))

@users_blueprint.route('/', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            u = User.query.filter_by(
                name=request.form['name']).first()
            if u is None:
                error = "Cannot find that username."
                return render_template('login.html', form=form, error=error)
            elif bcrypt.check_password_hash(
                    u.password, request.form['password']):
                session['logged_in'] = True
                session['user_id'] = u.id
                session['role'] = u.role
                session['name'] = u.name
                flash('You are logged in. Go Crazy.')
                return redirect(url_for('tasks.tasks'))
            else:
                error = 'Invalid password / username combination.'
                return render_template('login.html', form=form, error=error)
        else:
            return render_template('login.html', form=form, error=error)
    if request.method == 'GET':
        return render_template('login.html', form=form)

@users_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(
                form.name.data,
                form.email.data,
                bcrypt.generate_password_hash(form.password.data))
            try:
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering. Please login.')
                return redirect(url_for('users.login'))
            except IntegrityError:
                error = 'Snooze you lose. That username and/or email already exists.'
                return render_template('register.html', form=form, error=error)
        else:
            return render_template('register.html', form=form, error=error)
    if request.method == 'GET':
        return render_template('register.html', form=form)

project/templates/new_user_mail.html
User <b>{{ user.name }}</b> has joined.

project/templates/template.html
<!-- project/templates/template.html -->
{% extends "bootstrap/base.html" %}
{% block html_attribs %} lang="en"{% endblock %}

{% block title %}
	iGaming Analytics
{% endblock %}

{% block head %}
	<link rel="stylesheet" 
     href="//cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.0/paper/bootstrap.min.css">
	<link rel="stylesheet"
      href="{{url_for('static', filename='css/styles.css')}}">
     
{% endblock %}

{% block navbar %}
	<div class='navbar navbar-inverse navbar-fixed-top' role='navigation'>
	<div class='container'>
		<div class='navbar-header'>
			<button type="button" class='navbar-toggle' data-toggle='collapse' data target='.navbar-collapse'>
			<span class='sr-only'>Toggle navigation</span>
			<span class='icon-bar'></span>
			<span class='icon-bar'></span>
			<span class='icon-bar'></span>
			</button>
			<a href="/" class='navbar-brand'>iGaming Analytics</a>
		</div>
		<div class='collapse navbar-collapse'>
			<ul class='nav navbar-nav navbar-right'>
			{% if not session.logged_in %}
				<li><a href="{{ url_for('users.register') }}" title="">Signup</a></li>
			{% else %}
				<li><a href="{{ url_for('users.logout') }}" title="">Signout</a></li>
			{% endif %}
			{% if session.logged_in %}
			<li>
				<a>Welcome, {{username}}.</a>
			</li>
			{% endif %}
			</ul>
		</div>
	</div>
</div>
<!-- END NAVBAR -->
{% endblock %}

{% block content %}
	<div class='container'>
		<div class='row'>
			{% for message in get_flashed_messages() %}
				<div class='col-md-4 col-md-offset-4'>
					<div class="alert alert-info" role="alert">
					{{ message }}
					<button type="button" class='close' data-dismiss='alert'>
					&times;
					</button>
				</div>
				</div>
			{% endfor %}	
		</div>		
		{% if error %}
		<div class='row'>
			<div class='col-md-4 col-md-offset-4'>
				<div class="alert alert-danger" role="alert">
				<strong>Error: </strong>{{ error }}</div>
				<button type="button" class='close' data-dismiss='alert'>
					&times;
				</button>
			</div>	
		</div>
		{% elif get_flashed_messages() %}
		<!-- generate a blank div so you cant notice the page refresh -->
		{% else %}
			<div class='row' style='height:56px;'></div>
		{% endif %}
    
    {% block page_content %}
    	
    {% endblock %}
</div>
<div class='footer'>
		<hr>
		<p class='text-center'>&copy; <a href="http://rmdk.ca" title="">Authors webpage</a></p>
	</div>
{% endblock %}

{% block scripts %}
	{{ super() }}
	{{ moment.include_moment() }}
{% endblock %}